options:
    p: &c( 점령전 ) &f


function captureObjectGameInit(teamSize: number):
    set {BR.flag.borderSize} to 3000
    set {BR.flag.borderCenter.x} to random integer between -1000 and 1000
    set {BR.flag.borderCenter.z} to random integer between -1000 and 1000

    set {_x1} to {BR.flag.borderCenter.x} + ({BR.flag.borderSize} / 2)
    set {_x2} to {BR.flag.borderCenter.x} - ({BR.flag.borderSize} / 2)
    set {_z1} to {BR.flag.borderCenter.z} + ({BR.flag.borderSize} / 2)
    set {_z2} to {BR.flag.borderCenter.z} - ({BR.flag.borderSize} / 2)
    send "%{_x1}%,%{_x2}%,%{_z1}%,%{_z2}%" to all players

    set {CO.flag.inIngame} to true
    set {CO.flag.gametime} to 0
    set {CO.flag.timer} to 0
    set {CO.delay} to 300
    set {CO.flag.phase} to 1
    delete {CO.team.captures::*}
    teamInit({_teamSize})
    send "{@p} 게임이 시작되었습니다! 5분 뒤 거점 위치가 공개됩니다." to all players
    if {_teamSize} == 1:
        set {_message} to "&c레드 팀: 0"
    else if {_teamSize} == 2:
        set {_message} to "&c레드 팀: 0 &fvs &9블루 팀: 0"
    else if {_teamSize} == 3:
        set {_message} to "&c레드 팀: 0 &fvs &9블루 팀: 0 &fvs &a그린 팀: 0"
    else if {_teamSize} == 4:
        set {_message} to "&c레드 팀: 0 &fvs &9블루 팀: 0 &fvs &a그린 팀: 0 &fvs &e옐로 팀: 0"
    set {_bar} to boss bar with id "probar" with title "%{_message}%"
    remove all players from {_bar}
    set bar color of {_bar} to yellow
    set bar style of {_bar} to segmented 10
    add all players to {_bar}
    
    # 거점공개전:1 거점공개:2 거점활성화:3
    while {CO.flag.phase} > 0:
        add 1 to {CO.flag.gametime}
        add 1 to {CO.flag.timer}
        if {CO.flag.gametime} == 300:
            set {CO.flag.phase} to 2
            set {CO.flag.timer} to 0
            set bar color of {_bar} to purple
            set bar progress of {_bar} to 0
            createCaptureObject({_x1},{_x2},{_z1},{_z2})
        if {CO.flag.gametime} == 600:
            set {CO.flag.phase} to 3
            set {CO.flag.timer} to 0
            set bar color of {_bar} to white
            set bar progress of {_bar} to 0
        
        if {CO.flag.phase} is 1:
            set bar progress of {_bar} to ({CO.flag.timer} / 300) * 100
        if {CO.flag.phase} is 2:
            set bar progress of {_bar} to ({CO.flag.timer} / 300) * 100
            spawnParticlesInBorder("yellow")
        if {CO.flag.phase} is 3:
            spawnParticlesInBorder("red")
            checkCaptureObject({_bar})
        wait 1 second
    
    
    remove all players from {_bar}    
    stop


function createCaptureObject(x1:number,x2:number,z1:number,z2:number):
    send "%{_x1}%,%{_x2}%,%{_z1}%,%{_z2}%" to all players
    set {CO.flag.captureObject.centerX} to random integer from -1500 to 1500
    set {CO.flag.captureObject.centerZ} to random integer from -1500 to 1500
    set {CO.flag.captureObject.size} to (random integer from 1 to 3) * 10
    set {CO.flag.captureObject.x1} to {CO.flag.captureObject.centerX} - ({CO.flag.captureObject.size} / 2)
    set {CO.flag.captureObject.x2} to {CO.flag.captureObject.centerX} + ({CO.flag.captureObject.size} / 2)
    set {CO.flag.captureObject.z1} to {CO.flag.captureObject.centerZ} - ({CO.flag.captureObject.size} / 2)
    set {CO.flag.captureObject.z2} to {CO.flag.captureObject.centerZ} + ({CO.flag.captureObject.size} / 2)
    set {CO.flag.objloc} to location at {CO.flag.captureObject.centerX}, 256, {CO.flag.captureObject.centerZ} of the world "world"
    send "%{CO.flag.captureObject.centerX}%, %{CO.flag.captureObject.centerZ}% &f에 거점이 생성되었습니다. size:%{CO.flag.captureObject.size}%" to all players
    while block at {CO.flag.objloc} is air:
        set {_y} to y-coordinate of {CO.flag.objloc}
        set y-coordinate of {CO.flag.objloc} to {_y} - 1
    
function spawnParticlesInBorder(color: text):
    # 전역 변수에서 경계 좌표 가져오기
    set {_x1} to {CO.flag.captureObject.x1}
    set {_x2} to {CO.flag.captureObject.x2}
    set {_z1} to {CO.flag.captureObject.z1}
    set {_z2} to {CO.flag.captureObject.z2}
    set {_y} to y-coordinate of {CO.flag.objloc}
    set {_size} to {CO.flag.captureObject.size}
    set {_world} to "world"  # 월드는 오버월드로 제한
    set {_SEloc} to the location at {_x2}, {_y}+0.7, {_z2} of world "world"
    set {_SWloc} to the location at {_x2}, {_y}+0.7, {_z1} of world "world"
    set {_NWloc} to the location at {_x1}, {_y}+0.7, {_z1} of world "world"
    set {_NEloc} to the location at {_x1}, {_y}+0.7, {_z2} of world "world"
    if {_color} == "yellow":
        make 100 of dust using dustOption(yellow, 2) at {_SWloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(yellow, 2) at {_SEloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(yellow, 2) at {_NWloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(yellow, 2) at {_NEloc} with offset vector(0,10,0) with extra 0

        if {_size} == 10:
            make 80 of dust using dustOption(yellow, 2) at {_SEloc} with offset vector(-10,0,0) with extra 0
            make 80 of dust using dustOption(yellow, 2) at {_SWloc} with offset vector(0,0,-10) with extra 0
            make 80 of dust using dustOption(yellow, 2) at {_NWloc} with offset vector(10,0,0) with extra 0
            make 80 of dust using dustOption(yellow, 2) at {_NEloc} with offset vector(0,0,10) with extra 0
        else if {_size} == 20:
            make 100 of dust using dustOption(yellow, 2) at {_SEloc} with offset vector(-20,0,0) with extra 0
            make 100 of dust using dustOption(yellow, 2) at {_SWloc} with offset vector(0,0,-20) with extra 0
            make 100 of dust using dustOption(yellow, 2) at {_NWloc} with offset vector(20,0,0) with extra 0
            make 100 of dust using dustOption(yellow, 2) at {_NEloc} with offset vector(0,0,20) with extra 0
        else:
            make 140 of dust using dustOption(yellow, 2) at {_SEloc} with offset vector(-30,0,0) with extra 0
            make 140 of dust using dustOption(yellow, 2) at {_SWloc} with offset vector(0,0,-30) with extra 0
            make 140 of dust using dustOption(yellow, 2) at {_NWloc} with offset vector(30,0,0) with extra 0
            make 140 of dust using dustOption(yellow, 2) at {_NEloc} with offset vector(0,0,30) with extra 0
    else:
        make 100 of dust using dustOption(red, 2) at {_SWloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(red, 2) at {_SEloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(red, 2) at {_NWloc} with offset vector(0,10,0) with extra 0
        make 100 of dust using dustOption(red, 2) at {_NEloc} with offset vector(0,10,0) with extra 0

        if {_size} == 10:
            make 80 of dust using dustOption(red, 2) at {_SEloc} with offset vector(-10,0,0) with extra 0
            make 80 of dust using dustOption(red, 2) at {_SWloc} with offset vector(0,0,-10) with extra 0
            make 80 of dust using dustOption(red, 2) at {_NWloc} with offset vector(10,0,0) with extra 0
            make 80 of dust using dustOption(red, 2) at {_NEloc} with offset vector(0,0,10) with extra 0
        else if {_size} == 20:
            make 100 of dust using dustOption(red, 2) at {_SEloc} with offset vector(-20,0,0) with extra 0
            make 100 of dust using dustOption(red, 2) at {_SWloc} with offset vector(0,0,-20) with extra 0
            make 100 of dust using dustOption(red, 2) at {_NWloc} with offset vector(20,0,0) with extra 0
            make 100 of dust using dustOption(red, 2) at {_NEloc} with offset vector(0,0,20) with extra 0
        else:
            make 140 of dust using dustOption(red, 2) at {_SEloc} with offset vector(-30,0,0) with extra 0
            make 140 of dust using dustOption(red, 2) at {_SWloc} with offset vector(0,0,-30) with extra 0
            make 140 of dust using dustOption(red, 2) at {_NWloc} with offset vector(30,0,0) with extra 0
            make 140 of dust using dustOption(red, 2) at {_NEloc} with offset vector(0,0,30) with extra 0
            

function checkCaptureObject(bar : object):
    set {_x1} to {CO.flag.captureObject.x1}
    set {_x2} to {CO.flag.captureObject.x2}
    set {_z1} to {CO.flag.captureObject.z1}
    set {_z2} to {CO.flag.captureObject.z2}
    clear {_teamsInArea::*}  # 배열 초기화
    
    loop all players:
        set {_uuid} to uuid of loop-player
        set {_pteam} to {BR.player.team.%{_uuid}%}
        set {_loc} to location of loop-player
        if x-coordinate of {_loc} is between {_x1} and {_x2}:
            if z-coordinate of {_loc} is between {_z1} and {_z2}:
                if y-coordinate of {_loc} is between y-coordinate of {CO.flag.objloc} - 5 and y-coordinate of {CO.flag.objloc} + 10:
                    add {_pteam} to {_teamsInArea::*}
    clear {_uniqueTeams::*}  # 중복 제거를 위한 배열 초기화
    loop {_teamsInArea::*}:
        if loop-value is not in {_uniqueTeams::*}:
            add loop-value to {_uniqueTeams::*}
    
    if size of {_uniqueTeams::*} is 1:
        set {_capturingTeam} to {_uniqueTeams::1}
        add 1 to {CO.team.captures::%{_capturingTeam}%}
        set bar progress of {_bar} to ({CO.team.captures::%{_capturingTeam}%} / 60) * 100
        set bar title of {_bar} to "%{CO.team.captures::%{_capturingTeam}%}% / 60"
        send "&a거점에 &f%{_capturingTeam}% &a팀만 남아있습니다! 점수: %{CO.team.captures::%{_capturingTeam}%}%" to all players
        # 팀에 따라 보스바 색상 변경
        if {_capturingTeam} is 1:
            set bar color of {_bar} to red
        else if {_capturingTeam} is 2:
            set bar color of {_bar} to blue
        else if {_capturingTeam} is 3:
            set bar color of {_bar} to green
        else if {_capturingTeam} is 4:
            set bar color of {_bar} to yellow
        else:
            set bar color of {_bar} to white
        if {CO.team.captures::%{_capturingTeam}%} == 60:
            set {CO.flag.gametime} to 0
            set {CO.flag.timer} to 0
            set {CO.flag.phase} to 1
            if {_capturingTeam} is 1:
                add 1 to {CO.team.score.red}
            else if {_capturingTeam} is 2:
                add 1 to {CO.team.score.blue}
            else if {_capturingTeam} is 3:
                add 1 to {CO.team.score.green}
            else if {_capturingTeam} is 4:
                add 1 to {CO.team.score.yellow}
    else if size of {_uniqueTeams::*} > 1:
        send "&c거점에 여러 팀이 있습니다! 점수가 오르지 않습니다." to all players
        set bar color of {_bar} to purple  # 여러 팀이 있을 때 보스바 색상



command /captureObjectInit [<number>]:
    trigger:
        if arg 1 is not set:
            send "사용법: /captureObjectInit <팀수>" to player
            stop
        else:
            captureObjectGameInit(arg 1)

command /setPhase [<number>]:
    trigger:
        if arg 1 is not set:
            send "사용법: /setPhase <단계>" to player
            stop
        else:
            set {CO.flag.phase} to arg 1
            send "단계를 &c%{CO.flag.phase}%&f(으)로 설정했습니다." to player

command /setGameTime [<number>]:
    trigger:
        if arg 1 is not set:
            send "사용법: /setGameTime <시간>" to player
            stop
        else:
            set {CO.flag.gametime} to arg 1
            send "게임 시간을 &c%{CO.flag.gametime}%&f(으)로 설정했습니다." to player


command /objectDebug:
    trigger:
        make player execute command "/setPhase 0"
        captureObjectGameInit(1)
        make player execute command "/setGameTime 299"