options:
    p: &c( 배틀로얄 ) &f

function updateCompass():
    wait 2 seconds
    loop all players:
        set {_loc} to location of loop-player
        set x coordinate of {_loc} to {BR.flag.nextborderCenter.x}
        set z coordinate of {_loc} to {BR.flag.nextborderCenter.z}
        set loop-player's compass target to {_loc}
        send "{@p} 나침반이 업데이트 되었습니다" to loop-player

function brSuply():
    # set {_tmp} to {BR.flag.phase} + 1
    # set {_newsize} to {BR.data.borderSize::%{_tmp}%}
    # set {_coords::*} to makeRandomcenter({_newsize},10,{BR.flag.nextborderCenter.x},{BR.flag.nextborderCenter.z})
    # set {_x} to {_coords::1}
    # set {_z} to {_coords::2}
    # set {_tmploc} to location at {_x}, 256, {_z} of the world "world"
    # while block at {_tmploc} is air:
    #     set {_y} to y-coordinate of {_tmploc}
    #     set y-coordinate of {_tmploc} to {_y} - 1
    # set y-coordinate of {_tmploc} to {_y}
    # set block at {_tmploc} to chest
    # set {_int} to random integer between 1 and 5
    # set slot 0 of block at {_tmploc} to ({_int} of blaze rod)
    # set {_int} to random integer between 0 and 2
    # set slot 1 of block at {_tmploc} to ({_int} of netherite ingot)
    # set {_int} to random integer between 5 and 10
    # set slot 2 of block at {_tmploc} to ({_int} of quartz)
    # set {_int} to random integer between 5 and 8
    # set slot 3 of block at {_tmploc} to ({_int} of glowstone dust)
    # set {_int} to random integer between 64 and 64
    # set slot 4 of block at {_tmploc} to ({_int} of iron ingot)
    # set {_int} to random integer between 32 and 64
    # set slot 5 of block at {_tmploc} to ({_int} of iron ingot)
    # set {_int} to random integer between 10 and 30
    # set slot 6 of block at {_tmploc} to ({_int} of gold ingot)
    # broadcast "{@p} ( %{_x}%, %{_z}% ) 에 보급이 소환되었습니다!"
    set {CO.flag.supply.x} to random integer from 1000 to 3000
    set {CO.flag.supply.z} to random integer from 1000 to 3000
    send "&5( %{CO.flag.supply.x}%, %{CO.flag.supply.z}% ) 에 보급이 소환되었습니다" to all players
    set {_tmploc} to location at {CO.flag.supply.x}, 256, {CO.flag.supply.z} of the world "world"
    while block at {_tmploc} is air:
        set {_y} to y-coordinate of {_tmploc}
        set y-coordinate of {_tmploc} to {_y} - 1
    set {CO.flag.supply.y} to {_y}
    set block at {_tmploc} to chest
    set name of block at {_tmploc} to "보급상자"

# 보급 아이템 설정 명령어
command /보급설정:
    trigger:
        open chest inventory with 6 row named "보급 아이템 설정" to player
        loop {CO.items::*}:
            set slot (loop-counter)-1 of current inventory of player to loop-value

# 보급 아이템 저장
on inventory close:
    if name of current inventory of player is "보급 아이템 설정":
        delete {CO.items::*}
        loop 54 times:
            if slot (loop-counter)-1 of current inventory of player is not air:
                add slot (loop-counter)-1 of current inventory of player to {CO.items::*}
        send "&a보급 아이템이 설정되었습니다!" to player

# 보급 상자 클릭 이벤트
on click on chest:
    if name of event-block is "보급상자":
        cancel event
        set {_x} to x-coordinate of location of event-block
        set {_y} to y-coordinate of location of event-block
        set {_z} to z-coordinate of location of event-block

        # 설정된 보급 아이템 중 2개를 무작위로 선택
        set {_tmpItem::*} to {CO.items::*}
        set {_item1} to random element out of {_tmpItem::*}
        remove {_item1} from {_tmpItem::*} # 중복 방지
        set {_item2} to random element out of {_tmpItem::*}

        # 첫 번째 아이템 드랍
        if {_item1} is not air:
            drop {_item1} at location of event-block

        # 두 번째 아이템 드랍
        if {_item2} is not air:
            drop {_item2} at location of event-block

        # 상자 제거
        set block at location of event-block to air
        play sound "subtitle.entity.experience_orb.pickup" with volume 1 and pitch 1 to player

command /suplytest:
    trigger:
        brSuply()

command /밥:
    trigger:
        give 64 of bread to player

on join:
    set player's max health to 20
    heal player
on respawn:
    wait 1 tick
    set player's max health to 20
    heal player
on damage:
    if attacker is not player:
        set damage to damage / 2

on break:
    if event-block is iron ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of iron ingot at event-block
        set block at event-block to air
    if event-block is deepslate iron ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of iron ingot at event-block
        set block at event-block to air
    if event-block is gold ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of gold ingot at event-block
        set block at event-block to air
    if event-block is deepslate gold ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of gold ingot at event-block
        set block at event-block to air

    if event-block is copper ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of copper ingot at event-block
        set block at event-block to air
    if event-block is deepslate copper ore:
        cancel event
        set {_rnd} to random integer between 1 and 5
        drop {_rnd} of copper ingot at event-block
        set block at event-block to air
    if event-block is sand:
        cancel event
        set {_rnd} to random integer between 1 and 1
        drop {_rnd} of glass block at event-block
        set block at event-block to air


on rightclick:
    if player's tool is compass:
        open chest inventory with 3 row named "나침반 설정" to player
        set slot 3 of current inventory of player to green wool named "&a거점"
        set slot 5 of current inventory of player to chest named "&a보급상자"
        set {_teamNumber} to {BR.player.team.%uuid of player%}
        log "팀넘버: %{BR.flag.team.live.%{_teamNumber}%::*}%"
        set {_loc} to 0
        loop {BR.flag.team.live.%{_teamNumber}%::*}:
            log "플레이어: %{name of loop-player}%"
            set slot ({_loc}+19) of current inventory of player to skull of loop-value named "%{name of loop-player}%" 
            add 1 to {_loc}
on inventory click:
    if name of current inventory of player is "나침반 설정":
        if raw index of event-slot > 27: # outside custom inventory
            cancel event
        if index of event-slot is 3:
            if {CO.flag.phase} is 1:
                cancel event
                close player's inventory
                send "&c거점이 활성화 되지 않았습니다" to player
            else if {CO.flag.phase} is 0:
                cancel event
                close player's inventory
                send "&c거점이 활성화 되지 않았습니다" to player
            else:
                cancel event
                close player's inventory
                set player's compass target to location at {CO.captureObject.flag.centerX}, 0, {CO.captureObject.flag.centerZ} of the world "world"
                send "&a나침반이 거점으로 설정되었습니다" to player
        if index of event-slot is 5:
            cancel event
            close player's inventory
            set player's compass target to location at {CO.flag.supply.x}, {CO.flag.supply.y}, {CO.flag.supply.z} of the world "world"
            send "&a나침반이 보급 상자로 설정되었습니다" to player
        if index of event-slot is between 18 and 26:
            cancel event
            set {_target} to name of event-slot
            if {_target} is not air:
                set player's compass target to location of {_target}
                send "&a나침반이 %{_target}%을 추적합니다" to player
                close player's inventory
            else:
                send "&c어딜클릭하노" to player


on death of player:
    set {excludedItems::*} to iron ingot and gold ingot and copper ingot and netherite ingot and diamond and quartz and amethyst shard and glowstone dust 
    set {_x} to x-coordinate of victim's location
    set {_y} to y-coordinate of victim's location
    set {_z} to z-coordinate of victim's location
    set {_loc} to location at {_x}, {_y}, {_z} of the world "world"

    set victim's gamemode to spectator
    wait 1 tick
    teleport victim to {_loc}
    if {CO.flag.phase} >= 1:
        set {_item::*} to all items in victim's inventory
        loop {_item::*}:
            if loop-value is not air:
                if {excludedItems::*} contains loop-value:
                    drop loop-value
                    remove loop-value from victim's inventory

    set {_teamNunber} to {BR.player.team.%uuid of victim%}
    remove victim from {BR.flag.team.live.%{_teamNunber}%::*}

    send title "&c게임 중" to victim

    set {_time} to 0
    while {_time} < 5:
        send subtitle "&e%(5-{_time})%초 후 부활합니다" to victim
        send action bar "생존중인 팀원: %{BR.flag.team.live.%{_teamNunber}%::*}%" to victim
        set {_time} to {_time} + 1
        wait 1 second
    if size of {BR.flag.team.live.%{_teamNunber}%::*} is 0:
        if {CO.laf.phase} is 3:
            set {_x} to random integer between ({CO.captureObject.x1}+50) and ({CO.captureObject.x2}-50)
            set {_z} to random integer between ({CO.captureObject.z1}+50) and ({CO.captureObject.z2}-50)
            send subtitle "거점이 활성화되있어 거점 주변에 부활합니다" to victim
        else:    
            set {_x} to random integer from {CO.flag.x1} to {CO.flag.x2}
            set {_z} to random integer from {CO.flag.z1} to {CO.flag.z2}
        set {_y} to 256
        while block at location at {_x}, {_y}, {_z} is air:
            set {_y} to {_y} - 1
        set {_y} to {_y} + 1
        set {_loc} to location at {_x}, {_y}, {_z} of the world "world"
        loop {BR.flag.team.%{_teamNunber}%::*}:
            if loop-value is not in {BR.flag.team.live.%{_teamNunber}%::*}:
                add loop-value to {BR.flag.team.live.%{_teamNunber}%::*}
                teleport loop-value to {_loc}
                play sound "entity.ender_dragon.growl" with volume 1 and pitch 1 to loop-value
                send title "&c전멸" to loop-value
                set gamemode of loop-value to survival
    else:
        set {_teammate} to random element out of {BR.flag.team.live.%{_teamNunber}%::*}
        add victim to {BR.flag.team.live.%{_teamNunber}%::*}
        teleport victim to location of {_teammate}
        set gamemode of victim to survival

    if {CO.flag.phase} is 0:
        send title "&e5초 후 부활합니다" to victim
        wait 5 seconds
        set {_tmpX} to x-coordinate of {_loc}
        set {_x} to random integer from ({_tmpX}-15) to ({_tmpX}+15)
        set {_tmpZ} to z-coordinate of {_loc}
        set {_z} to random integer from ({_tmpZ}-15) to ({_tmpZ}+15)
        set {_y} to 256
        while block at location at {_x}, {_y}, {_z} is air:
            set {_y} to {_y} - 1
        set {_y} to {_y} + 1
        teleport victim to location at {_x}, {_y}, {_z} in world "world"
        set gamemode of victim to survival
        heal victim

on death:
    if attacker is player:
        set {_rnd} to random integer between 1 and 3
        drop {_rnd} of gunpowder at victim's location
        chance of 35%:
            drop 1 of amethyst shard at victim's location

# on respawn:
#     wait 1 tick

#     loop all items in player's inventory:
#         if loop-value is {droppedItems::%uuid of player%::*}:
#             remove loop-value from player's inventory